// <auto-generated />
using System;
using ConnectSea.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectSea.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ConnectSeaContext))]
    [Migration("20251223164042_ManifestoEscala")]
    partial class ManifestoEscala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectSea.Domain.Entities.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Eta")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Etb")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Etd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Porto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Escalas", (string)null);
                });

            modelBuilder.Entity("ConnectSea.Domain.Entities.Manifesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PortoDestino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortoOrigem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Manifestos", (string)null);
                });

            modelBuilder.Entity("ConnectSea.Domain.Entities.ManifestoEscala", b =>
                {
                    b.Property<int>("ManifestoId")
                        .HasColumnType("int");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataVinculacao")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ManifestoId", "EscalaId");

                    b.HasIndex("EscalaId");

                    b.ToTable("ManifestoEscalas", (string)null);
                });

            modelBuilder.Entity("ConnectSea.Domain.Entities.ManifestoEscala", b =>
                {
                    b.HasOne("ConnectSea.Domain.Entities.Escala", "Escala")
                        .WithMany()
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnectSea.Domain.Entities.Manifesto", "Manifesto")
                        .WithMany("ManifestoEscalas")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("ConnectSea.Domain.Entities.Manifesto", b =>
                {
                    b.Navigation("ManifestoEscalas");
                });
#pragma warning restore 612, 618
        }
    }
}
